#!/bin/sh
# PlantUML Launcher
#
# This script is free software; you can redistribute it and/or modify it
# under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This script is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
# or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public
# License for more details.
# You should have received a copy of the GNU General Public
# License along with this library; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301,
# USA.
#
# Copyright (C) 2010 Ilya Paramonov <ivparamonov@gmail.com>

# Use Java 11 explicitly for PlantUML
JAVA="/usr/lib/jvm/java-11-openjdk-amd64/bin/java"

# Check if Java 11 is available
if [ ! -x "$JAVA" ]; then
    echo "Cannot find Java 11 at $JAVA. Please ensure it is installed."
    exit 1
fi

HEADLESS=
[ -z "$DISPLAY" ] && HEADLESS=-Djava.awt.headless=true

exec "$JAVA" $HEADLESS -jar /usr/share/plantuml/plantuml.jar "$@"
