server:
  servlet:
    context-path: /api

spring:
  application:
    name: jogo-acoes
  profiles:
    default: sandbox
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
  session:
    store-type: jdbc
    timeout: 30d
