-- Same schema as db/migration/V1__create_email_template_table.sql (Postgres), H2 dialect for
-- fast tests (H2 2.x's native JSON column type stands in for Postgres's JSONB).
CREATE TABLE email_template (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    client_id VARCHAR(255) NOT NULL,
    name VARCHAR(255) NOT NULL,
    subject CLOB NOT NULL,
    body CLOB NOT NULL,
    variables_schema JSON,
    ses_template_name VARCHAR(510) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    UNIQUE (client_id, name)
);
