#!/usr/bin/env bash
# Spec 05-014 -- dumps the JaCoCo runtime agent's accumulated execution data from the `app`
# container (docker-compose.blackbox.yml, tcpserver mode on port 6300) and turns it into an
# HTML coverage report. Run this after exercising the application externally (Swagger UI
# and/or the Python blackbox suite, spec 05-015) against `docker compose -f docker-compose.yml
# -f docker-compose.blackbox.yml up`.
#
# Separate from, and never overwrites, the JUnit/Cucumber suite's own report
# (target/site/jacoco/, generated by `mvn test`/`mvn verify` via jacoco-maven-plugin) -- that
# one measures a different kind of exercise of the same code.
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
APP_DIR="$REPO_ROOT/app"
JACOCO_CLI="$APP_DIR/target/jacoco/jacococli.jar"
DUMP_FILE="$APP_DIR/target/jacoco-blackbox.exec"
REPORT_DIR="$REPO_ROOT/target/site/jacoco-blackbox"
HOST="${JACOCO_DUMP_HOST:-localhost}"
PORT="${JACOCO_DUMP_PORT:-6300}"

if [ ! -f "$JACOCO_CLI" ]; then
  echo "jacococli.jar not found at $JACOCO_CLI -- run 'mvn -pl app package' first (copies it via maven-dependency-plugin)." >&2
  exit 1
fi

echo "Dumping JaCoCo execution data from $HOST:$PORT..."
java -jar "$JACOCO_CLI" dump --address "$HOST" --port "$PORT" --destfile "$DUMP_FILE"

echo "Generating HTML report at $REPORT_DIR..."
java -jar "$JACOCO_CLI" report "$DUMP_FILE" \
  --classfiles "$APP_DIR/target/classes" \
  --sourcefiles "$APP_DIR/src/main/java" \
  --html "$REPORT_DIR"

echo "Done: $REPORT_DIR/index.html"
